@startuml
interface uca.core.servicio.interfaces.iReservaServicio {
~ void altaReserva(int,int,String,String)
~ String checkout(int)
~ String checkin(int)
~ Reserva buscarReserva(int)
~ Collection<Reserva> buscarReserva(String,String)
~ int getCantidadReservas()
~ void eliminarReserva(int)
~ void cancelarReserva(int)
~ void setEstadoReserva(int,String)
~ void setPrecioTotal(int,float)
~ void setAutocaravana(int,int)
~ void setCliente(int,int)
~ void setFechaIni(int,String)
~ void setFechaFin(int,String)
~ void setPrecioTotal(int,BigDecimal)
~ void modificarReservaEnCurso(int,String)
~ void modificarReserva(int,int,String,String)
~ Collection<Reserva> getListaReservas()
~ String crearEstado(String)
~ String eliminarEstado(String)
}
class uca.dss.SpringCli.SpringCliApplicationTests {
}
class uca.core.servicio.implementaciones.reglas.ReservaReglas {
~ iReservaRepositorio reservaRepositorio
~ iClienteServicio clienteServicio
~ iAutocaravanaServicio autocaravanaServicio
+ BigDecimal calculaPrecioTotal(Autocaravana,Cliente,LocalDate,LocalDate)
+ boolean condicionesCancelacion(Reserva)
+ boolean condicionesModificacion(Reserva)
+ boolean condicionesFinalizacion(Reserva)
+ BigDecimal calcularTasaCancelacion(Reserva)
+ BigDecimal calcularTasaModificacion(Reserva)
+ BigDecimal calcularTasaFinalizacion(Reserva)
+ BigDecimal calcularMulta(Reserva)
+ BigDecimal calcularTasaAcabadaSinCheckOut(Reserva)
+ boolean comprobarAutocaravana(Autocaravana)
+ boolean comprobarCliente(Cliente)
+ boolean comprobarReserva(LocalDate,LocalDate,Autocaravana,Cliente)
}
class uca.core.servicio.implementaciones.ReservaServicioImpl {
- ReservaReglas reservaReglas
- iReservaRepositorio reservaRepositorio
- iEstadoRepositorio reservaEstadoRepositorio
- AutocaravanaServicioImpl autocaravanaServicio
- ClienteServicioImpl clienteServicio
+ void altaReserva(int,int,String,String)
+ String checkout(int)
+ String checkin(int)
+ Reserva buscarReserva(int)
+ Collection<Reserva> buscarReserva(String,String)
+ int getCantidadReservas()
+ void eliminarReserva(int)
+ void cancelarReserva(int)
+ void setEstadoReserva(int,String)
+ void setPrecioTotal(int,float)
+ void setAutocaravana(int,int)
+ void setCliente(int,int)
+ void setFechaIni(int,String)
+ void setFechaFin(int,String)
+ void setPrecioTotal(int,BigDecimal)
+ void modificarReservaEnCurso(int,String)
+ void modificarReserva(int,int,String,String)
+ Collection<Reserva> getListaReservas()
+ String crearEstado(String)
+ String eliminarEstado(String)
}
interface uca.core.servicio.interfaces.iAutocaravanaServicio {
~ void altaAutocaravana(String,BigDecimal,int,String,int)
~ void comprobarAutocaravana(String,BigDecimal,int,String,int)
~ Autocaravana buscarAutocaravana(int)
~ Collection<Autocaravana> buscarAutocaravana(String,String)
~ Collection<Autocaravana> getListaAutocaravanas()
~ Collection<String> getListaEstadoAutocaravana()
~ boolean quedanCaravanas()
~ boolean comprobarEstadoAutocaravana(String)
~ void setModelo(int,String)
~ void setModelo(String,String)
~ void setPrecioPorDia(int,BigDecimal)
~ void setPrecioPorDia(String,BigDecimal)
~ void setPlazas(int,int)
~ void setPlazas(String,int)
~ void setEstado(int,String)
~ void setEstado(String,String)
~ void setKilometraje(int,int)
~ void setKilometraje(String,int)
~ void eliminarAutocaravana(int)
~ void eliminarAutocaravana(String)
~ void eliminarEstadoAutocaravana(String)
~ void addEstadoAutocaravana(String)
~ void setPrecio(String,BigDecimal)
~ void setPrecio(int,BigDecimal)
~ String crearEstado(String)
~ String eliminarEstado(String)
}
class uca.SpringCli.SpringCliApplicationTests {
~ void contextLoads()
}
class uca.core.servicio.implementaciones.ClienteServicioImpl {
- iClienteRepositorio clienteRepositorio
- iEstadoRepositorio clienteEstadoRepositorio
- ClienteReglas clienteReglas
+ void altaCliente(String,String,String,String,String,String)
+ int getNumeroClientes()
+ Cliente buscarCliente(int)
+ Cliente buscarCliente(String)
+ Collection<Cliente> buscarCliente(String,String)
+ void eliminarCliente(String)
+ void eliminarCliente(int)
+ void comprobarCliente(String,String,String,String,String,String)
+ void setNombre(int,String)
+ void setNombre(String,String)
+ void setApellido(int,String)
+ void setApellido(String,String)
+ void setEmail(String,String)
+ void setEmail(int,String)
+ void setDni(int,String)
+ void setFechaNacimiento(String,String)
+ void setFechaNacimiento(int,String)
+ void setTelefono(int,String)
+ void setTelefono(String,String)
+ String eliminarEstado(String)
+ String crearEstado(String)
+ Collection<String> getListaEstadoclientes()
+ Collection<Cliente> getListaClientes()
+ void guardarCliente(Cliente)
}
interface uca.core.dao.iAutocaravanaRepositorio {
~ void guardarAutocaravana(Collection<Autocaravana>)
~ void guardarAutocaravana(Autocaravana)
~ Collection<Autocaravana> cargarAutocaravana()
~ Autocaravana buscarAutocaravana(int)
~ Collection<Autocaravana> buscarAutocaravana(String,String)
~ void eliminarAutocaravana(String)
~ void eliminarAutocaravana(int)
}
interface uca.core.dao.iEstadoRepositorio {
~ void guardarEstado(Estado)
~ void guardarEstado(List<Estado>)
~ void eliminarEstado(Estado)
~ Estado cargarEstadoDefault(String)
~ List<String> cargarEstado(String)
}
class uca.core.dominio.Cliente {
- int idC
- String nombre
- String apellido
- String telefono
- String email
- String dni
- String fechaNacimiento
- int cantidadReservasRealizadas
- int multas
- String estado
+ {static} Cliente ClienteNulo
+ int Edad()
+ void setNuevaMulta()
+ void setNuevaReservaRealizada()
}
class uca.core.dominio.Autocaravana {
- int vecesReservada
- int idA
- String matricula
- int plazas
- String modelo
- BigDecimal precioPorDia
- int kilometraje
- String estadoA
+ void setNuevaReservaRealizada()
+ String toString()
}
class uca.core.dominio.Reserva {
- int idR
- int idCliente
- int idAutocaravana
- String fechaIni
- String fechaFin
- String estadoR
- BigDecimal precioTotal
- BigDecimal pagado
+ boolean estaPagada()
+ LocalDate fechaFinF()
+ LocalDate fechaIniF()
+ String toString()
}
class uca.core.servicio.implementaciones.reglas.AutocaravanaReglas {
+ boolean comprobarMatricula(String)
}
interface uca.core.dao.iClienteRepositorio {
~ void guardarCliente(Collection<Cliente>)
~ void guardarCliente(Cliente)
~ Collection<Cliente> cargarCliente()
~ Cliente buscarCliente(int)
~ Collection<Cliente> buscarCliente(String,String)
~ void eliminarCliente(String)
~ void eliminarCliente(int)
}
class uca.core.servicio.implementaciones.AutocaravanaServicioImpl {
- iAutocaravanaRepositorio autocaravanaRepositorio
- iEstadoRepositorio autocaravanaEstadoRepositorio
- AutocaravanaReglas autocaravanaReglas
+ void altaAutocaravana(String,BigDecimal,int,String,int)
+ void comprobarAutocaravana(String,BigDecimal,int,String,int)
+ Autocaravana buscarAutocaravana(int)
+ Collection<Autocaravana> buscarAutocaravana(String,String)
+ Collection<Autocaravana> getListaAutocaravanas()
+ Collection<String> getListaEstadoAutocaravana()
+ boolean quedanCaravanas()
+ boolean comprobarEstadoAutocaravana(String)
+ void setModelo(int,String)
+ void setModelo(String,String)
+ void setPrecioPorDia(int,BigDecimal)
+ void setPrecioPorDia(String,BigDecimal)
+ void setPlazas(int,int)
+ void setPlazas(String,int)
+ void setEstado(int,String)
+ void setEstado(String,String)
+ void setKilometraje(int,int)
+ void setKilometraje(String,int)
+ void eliminarAutocaravana(int)
+ void eliminarAutocaravana(String)
+ void eliminarEstadoAutocaravana(String)
+ void addEstadoAutocaravana(String)
+ void setPrecio(String,BigDecimal)
+ void setPrecio(int,BigDecimal)
+ String crearEstado(String)
+ String eliminarEstado(String)
}
interface uca.core.dao.iReservaRepositorio {
~ void guardarReserva(Collection<Reserva>)
~ void guardarReserva(Reserva)
~ Collection<Reserva> cargarReserva()
~ Collection<Reserva> buscarReserva(String,String)
~ Reserva buscarReserva(int)
~ void eliminarReserva(int)
}
class uca.core.dominio.Estado {
~ String tipo
~ String valor
}
class uca.core.servicio.implementaciones.reglas.ClienteReglas {
~ iClienteRepositorio clienteRepositorio
+ boolean comprobarDNI(String)
+ boolean comprobarEdad(int)
+ void comprobarTelefono(Cliente,String)
}
interface uca.core.servicio.interfaces.iClienteServicio {
~ void altaCliente(String,String,String,String,String,String)
~ int getNumeroClientes()
~ Cliente buscarCliente(int)
~ Cliente buscarCliente(String)
~ Collection<Cliente> buscarCliente(String,String)
~ void eliminarCliente(String)
~ void eliminarCliente(int)
~ void comprobarCliente(String,String,String,String,String,String)
~ void setNombre(int,String)
~ void setNombre(String,String)
~ void setApellido(int,String)
~ void setApellido(String,String)
~ void setEmail(String,String)
~ void setEmail(int,String)
~ void setDni(int,String)
~ void setFechaNacimiento(String,String)
~ void setFechaNacimiento(int,String)
~ void setTelefono(int,String)
~ void setTelefono(String,String)
~ Collection<String> getListaEstadoclientes()
~ Collection<Cliente> getListaClientes()
~ void guardarCliente(Cliente)
~ String crearEstado(String)
~ String eliminarEstado(String)
}


uca.core.servicio.interfaces.iReservaServicio <|.. uca.core.servicio.implementaciones.ReservaServicioImpl
uca.core.servicio.interfaces.iClienteServicio <|.. uca.core.servicio.implementaciones.ClienteServicioImpl
uca.core.servicio.interfaces.iAutocaravanaServicio <|.. uca.core.servicio.implementaciones.AutocaravanaServicioImpl
@enduml